### ISSUE TITLE
table symbol error

### ISSUE THREAD

**Issue by S11720037** [DenisSamilton/CppConsoleTable#17]
![Screenshot from 2019-04-29 17-15-43](https://user-images.githubusercontent.com/50015208/56886828-7a437c00-6aa2-11e9-8c48-027ffb301bbb.png)

**Comment by Oradle** [comment]
Hi @S11720037 ! Thank for your participating and opening issue! 
Unfortunate, this isn't really a bug. This is caused because of encoding difference. The standard symbols preset for table is made for **CP866**, and as far as I see, your terminal uses different one. Try to switch your terminal encoding to **CP866** if it's okay for you, or create your own `TableChars` struct and assign your own symbols for your encoding.
How to do it is decribed in [README.md](https://github.com/Oradle/CppConsoleTable/blob/master/README.md). Here is the screenshot from there:

![image](https://user-images.githubusercontent.com/22996142/56929902-a6332180-6ae3-11e9-903e-289fc9e27174.png)

**Comment by DenisSamilton** [comment]
Because of that problem I decided to make a new feature #20 that can be a solution of your problem. Wait for it in v1.4.0 release
